# Generated by Django 5.2 on 2025-06-24 08:04

import bwf_forms.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BwfForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version_id', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BwfFormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(default=bwf_forms.models.get_unique_form_version_id, max_length=60, unique=True)),
                ('version_number', models.IntegerField(default=1)),
                ('definition', models.JSONField(blank=True, null=True)),
                ('form_file', models.FileField(blank=True, max_length=1000, null=True, storage=django.core.files.storage.FileSystemStorage(location='/data/data/projects/spatial-layer-monitor/private-media'), upload_to=bwf_forms.models.upload_to_path)),
                ('is_edition', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_on', models.DateTimeField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bwf_forms.bwfform')),
            ],
            options={
                'unique_together': {('form', 'version_id')},
            },
        ),
    ]
